package com.yumesplugins.purehelper;

enum EvaluationReasonCode
{
	NONE,
	FIXED_REWARD_AVOIDED_SKILL_XP,
	CHOICE_REWARD_AVOIDED_SKILL_XP,
	UNMODELED_CHOICE_REWARD,
	PREREQUISITE_BLOCKED,
	SKILL_REQUIREMENT_EXCEEDS_CAP,
	SKILL_REQUIREMENT_PROTECTED
}
